// Reference documentation for :sdk and :openrouter-kotlin-testing, generated by Dokka 2.2.0 over manually registered
// source roots. This is a SIBLING project on purpose: Dokka bundles a jackson-core whose classloader must never meet
// the sdkgen plugin's YAML parser (`generateOpenrouterSdk` fails with NoSuchMethodError YAMLParser._updateToken
// otherwise). Never apply org.jetbrains.dokka to :sdk, :openrouter-kotlin-testing, or the root project.
import org.jetbrains.dokka.gradle.engine.parameters.KotlinPlatform
import org.jetbrains.dokka.gradle.tasks.DokkaGeneratePublicationTask

plugins {
    alias(libs.plugins.dokka)
}

// The generated snapshot is produced by :sdk; consume its `sources` dir through a task dependency, not by applying
// the sdkgen plugin here.
val generatedSources = rootProject.layout.projectDirectory.dir("sdk/build/generated/sdkgen/openrouter/sources")

// JVM variants of the SDK's compile dependencies, for Dokka's symbol resolution.
val dokkaClasspath: Configuration by configurations.creating {
    isCanBeConsumed = false
    isCanBeResolved = true
    attributes {
        attribute(Usage.USAGE_ATTRIBUTE, objects.named(Usage.JAVA_API))
        attribute(Category.CATEGORY_ATTRIBUTE, objects.named(Category.LIBRARY))
        attribute(LibraryElements.LIBRARY_ELEMENTS_ATTRIBUTE, objects.named(LibraryElements.JAR))
        attribute(Attribute.of("org.jetbrains.kotlin.platform.type", String::class.java), "jvm")
    }
}
dependencies {
    dokkaClasspath("org.jetbrains.kotlin:kotlin-stdlib:${libs.versions.kotlin.get()}")
    dokkaClasspath(libs.sdkgen.runtime)
    dokkaClasspath(libs.sdkgen.transport.ktor)
    dokkaClasspath(libs.sdkgen.testing)
    dokkaClasspath(libs.kotlinx.serialization.json)
    dokkaClasspath(libs.kotlinx.coroutines.core)
    dokkaClasspath(libs.ktor.client.core)
}

dokka {
    moduleName.set("openrouter-kotlin")
    dokkaSourceSets.register("openrouter") {
        analysisPlatform.set(KotlinPlatform.JVM)
        sourceRoots.from(
            rootProject.layout.projectDirectory.dir("sdk/src/commonMain/kotlin"),
            rootProject.layout.projectDirectory.dir("sdk/src/jvmMain/kotlin"),
            rootProject.layout.projectDirectory.dir("testing/src/commonMain/kotlin"),
            generatedSources,
        )
        classpath.from(dokkaClasspath)
        includes.from(rootProject.layout.projectDirectory.file("docs/api/module.md"))
        // The generated API is public and SemVer-governed (ADR 0001): document it.
        suppressGeneratedFiles.set(false)
        perPackageOption {
            matchingRegex.set("""com\.nabobery\.openrouter\.internal.*""")
            suppress.set(true)
        }
        sourceLink {
            localDirectory.set(rootProject.layout.projectDirectory.dir("sdk/src"))
            remoteUrl("https://github.com/nabobery/openrouter-kotlin/tree/main/sdk/src")
            remoteLineSuffix.set("#L")
        }
    }
}

tasks.named("dokkaGeneratePublicationHtml") { dependsOn(":sdk:generateOpenrouterSdk") }

// The FULL Dokka HTML site, exposed for the GitHub Pages workflow (docs.yml). It is intentionally NOT what the
// published -javadoc.jars carry: the generated surface makes the site ~100 MB, and embedding it in all 24
// publications would push the Central upload bundle past 2 GB (Central's soft limit is ~78 MB/month). See dokkaJavadoc.
configurations.consumable("dokkaHtml") {
    attributes { attribute(Attribute.of("com.nabobery.openrouter.dokka", String::class.java), "html") }
    outgoing.artifact(
        tasks.named<DokkaGeneratePublicationTask>("dokkaGeneratePublicationHtml")
            .flatMap { it.outputDirectory },
    )
}

// The lightweight payload the published -javadoc.jars carry: Central requires a -javadoc.jar per artifact, but the
// real reference lives on GitHub Pages (the full site above) and in the source KDoc. This overview satisfies the
// requirement at a few KB per jar and points readers to the hosted site and the guides.
val javadocOverviewDir = layout.buildDirectory.dir("javadoc-overview")
val javadocOverview = tasks.register("javadocOverview") {
    description = "Small HTML overview packed into every published -javadoc.jar (points to the hosted Dokka site)."
    val out = javadocOverviewDir
    outputs.dir(out)
    doLast {
        val dir = out.get().asFile
        dir.mkdirs()
        dir.resolve("index.html").writeText(
            """
            <!DOCTYPE html>
            <html lang="en">
            <head><meta charset="utf-8"><title>openrouter-kotlin &#8212; API reference</title></head>
            <body>
            <h1>openrouter-kotlin</h1>
            <p>Kotlin Multiplatform client for the OpenRouter API, generated from the pinned OpenAPI contract with a
            curated facade.</p>
            <p>The complete generated API reference (Dokka) is published at
            <a href="https://nabobery.github.io/openrouter-kotlin/">https://nabobery.github.io/openrouter-kotlin/</a>.</p>
            <p>Task-oriented tutorials and how-tos:
            <a href="https://github.com/nabobery/openrouter-kotlin/tree/main/docs/guides">docs/guides</a>.</p>
            <p>KDoc accompanies every public declaration in the sources.</p>
            </body>
            </html>
            """.trimIndent() + "\n",
        )
    }
}

// Consumed by the javadoc-jar tasks in :sdk / :testing (gradle/openrouter-publication.gradle.kts).
configurations.consumable("dokkaJavadoc") {
    attributes { attribute(Attribute.of("com.nabobery.openrouter.dokka", String::class.java), "javadoc") }
    outgoing.artifact(javadocOverviewDir) { builtBy(javadocOverview) }
}
