#!/usr/bin/env python3
"""Tests for merge-verification-metadata.py — the union merge of per-host Gradle
dependency-verification metadata files."""
from __future__ import annotations

import pathlib
import subprocess
import sys
import tempfile
import unittest

SCRIPT = pathlib.Path(__file__).with_name("merge-verification-metadata.py")
NS = "https://schema.gradle.org/dependency-verification"


def _doc(components: str) -> str:
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        f'<verification-metadata xmlns="{NS}">\n'
        "   <configuration>\n"
        "      <verify-metadata>true</verify-metadata>\n"
        "      <verify-signatures>false</verify-signatures>\n"
        "   </configuration>\n"
        "   <components>\n"
        f"{components}"
        "   </components>\n"
        "</verification-metadata>\n"
    )


def _component(group: str, name: str, version: str, artifact: str, sha: str) -> str:
    return (
        f'      <component group="{group}" name="{name}" version="{version}">\n'
        f'         <artifact name="{artifact}">\n'
        f'            <sha256 value="{sha}" origin="Generated by Gradle"/>\n'
        f"         </artifact>\n"
        f"      </component>\n"
    )


class MergeVerificationMetadataTest(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = tempfile.TemporaryDirectory()
        self.dir = pathlib.Path(self.tmp.name)

    def tearDown(self) -> None:
        self.tmp.cleanup()

    def _write(self, name: str, *components: str) -> pathlib.Path:
        p = self.dir / name
        p.write_text(_doc("".join(components)))
        return p

    def _run(self, out: pathlib.Path, *inputs: pathlib.Path) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            [sys.executable, str(SCRIPT), "--output", str(out), *[str(i) for i in inputs]],
            capture_output=True,
            text=True,
        )

    def test_union_keeps_every_artifact_once_sorted(self) -> None:
        a = self._write(
            "a.xml",
            _component("org.x", "x", "1.0", "x-1.0.jar", "AAA"),
            _component("org.y", "y", "1.0", "y-1.0.jar", "YYY"),
        )
        # b overlaps x (same sha) and adds a disjoint z.
        b = self._write(
            "b.xml",
            _component("org.x", "x", "1.0", "x-1.0.jar", "AAA"),
            _component("org.z", "z", "1.0", "z-1.0.jar", "ZZZ"),
        )
        out = self.dir / "merged.xml"
        result = self._run(out, a, b)
        self.assertEqual(0, result.returncode, result.stderr)
        text = out.read_text()
        # every artifact present exactly once
        self.assertEqual(1, text.count('name="x-1.0.jar"'), text)
        self.assertEqual(1, text.count('name="y-1.0.jar"'), text)
        self.assertEqual(1, text.count('name="z-1.0.jar"'), text)
        # sorted: x before y before z (org.x < org.y < org.z)
        self.assertLess(text.index("org.x"), text.index("org.y"))
        self.assertLess(text.index("org.y"), text.index("org.z"))
        # shas preserved
        self.assertIn('value="AAA"', text)
        self.assertIn('value="ZZZ"', text)

    def test_conflicting_checksum_for_one_artifact_fails(self) -> None:
        a = self._write("a.xml", _component("org.x", "x", "1.0", "x-1.0.jar", "AAA"))
        # same artifact, different sha256 → conflict.
        b = self._write("b.xml", _component("org.x", "x", "1.0", "x-1.0.jar", "BBB"))
        out = self.dir / "merged.xml"
        result = self._run(out, a, b)
        self.assertNotEqual(0, result.returncode, "conflicting checksums must fail")
        self.assertIn("x-1.0.jar", result.stdout + result.stderr)
        self.assertFalse(out.exists(), "no output should be written on conflict")


if __name__ == "__main__":
    unittest.main()
