#!/usr/bin/env python3
"""Merge per-host Gradle dependency-verification metadata into one sha256 union.

Each CI host (ubuntu / macos / windows / macos-intel) executes the cold-cache
verification and isolated-publication task graph with
`--write-verification-metadata sha256`. This unions the resolved dependencies
into a single
`gradle/verification-metadata.xml`: every `<artifact>`/`<sha256>` is kept once,
sorted deterministically, and a **conflicting** checksum for the same artifact
(the same coordinate resolving to two different bytes) is a hard error — that is
the tampering signal the control exists to catch — so nothing is written.

Usage:
  merge-verification-metadata.py --output gradle/verification-metadata.xml IN.xml [IN.xml ...]
"""
from __future__ import annotations

import argparse
import sys
import xml.etree.ElementTree as ET

NS = "https://schema.gradle.org/dependency-verification"
ET.register_namespace("", NS)


def _q(tag: str) -> str:
    return f"{{{NS}}}{tag}"


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--output", required=True)
    ap.add_argument("inputs", nargs="+")
    args = ap.parse_args(argv)

    # component key (group, name, version) -> artifact name -> (sha256 value, origin)
    components: dict[tuple[str, str, str], dict[str, tuple[str, str]]] = {}
    configuration: ET.Element | None = None
    conflicts: list[str] = []

    for path in args.inputs:
        root = ET.parse(path).getroot()
        if configuration is None:
            cfg = root.find(_q("configuration"))
            if cfg is not None:
                configuration = cfg
        for comp in root.iterfind(f"{_q('components')}/{_q('component')}"):
            key = (comp.get("group", ""), comp.get("name", ""), comp.get("version", ""))
            artifacts = components.setdefault(key, {})
            for art in comp.iterfind(_q("artifact")):
                aname = art.get("name", "")
                sha = art.find(_q("sha256"))
                if sha is None:
                    continue
                value = sha.get("value", "")
                origin = sha.get("origin", "Generated by Gradle")
                existing = artifacts.get(aname)
                if existing is not None and existing[0] != value:
                    conflicts.append(
                        f"{key[0]}:{key[1]}:{key[2]} {aname}: {existing[0]} != {value}"
                    )
                else:
                    artifacts[aname] = (value, origin)

    if conflicts:
        print("merge-verification-metadata: CONFLICTING checksums (refusing to write):", file=sys.stderr)
        for c in conflicts:
            print(f"  {c}", file=sys.stderr)
        return 1

    out_root = ET.Element(_q("verification-metadata"))
    if configuration is not None:
        out_root.append(configuration)
    else:
        cfg = ET.SubElement(out_root, _q("configuration"))
        ET.SubElement(cfg, _q("verify-metadata")).text = "true"
        ET.SubElement(cfg, _q("verify-signatures")).text = "false"
    comps_el = ET.SubElement(out_root, _q("components"))
    for key in sorted(components):
        comp_el = ET.SubElement(comps_el, _q("component"), group=key[0], name=key[1], version=key[2])
        for aname in sorted(components[key]):
            value, origin = components[key][aname]
            art_el = ET.SubElement(comp_el, _q("artifact"), name=aname)
            ET.SubElement(art_el, _q("sha256"), value=value, origin=origin)

    ET.indent(out_root, space="   ")
    tree = ET.ElementTree(out_root)
    with open(args.output, "wb") as f:
        f.write(b'<?xml version="1.0" encoding="UTF-8"?>\n')
        tree.write(f, encoding="utf-8", xml_declaration=False)
        f.write(b"\n")
    total = sum(len(a) for a in components.values())
    print(f"merge-verification-metadata: wrote {args.output} ({len(components)} components, {total} artifacts)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
